[package]
name = "melbi-teeny-vec"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
static_assertions.workspace = true

[dev-dependencies]
criterion.workspace = true
smallvec.workspace = true

[[bench]]
name = "teeny_vec"
harness = false

[lints]
workspace = true

