[package]
name = "melbi-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "melbi-lsp"
path = "src/main.rs"

[lib]
name = "melbi_lsp"
path = "src/lib.rs"

[dependencies]
melbi-core.workspace = true
melbi-fmt.workspace = true
tokio = { version = "1.47.1", features = ["full"] }
pest.workspace = true
tower-lsp = "0.20.0"
tree-sitter.workspace = true
tree-sitter-melbi.workspace = true
bumpalo = "3.16.0"
dashmap = "6.1.0"
