//! Builds real Melbi expressions across the two mutually recursive trees.
//!
//! Compare with what this needed under the one-builder-per-tree design: two
//! builder structs, two `TreeBuilder` impls generated by a macro because the
//! storage halves were identical, and a pair of `<Expr = Self>` / `<Lit = Self>`
//! impls to tie them together. All of that is gone. There is one builder, the
//! two trees are named by their descriptors, and the passes below cross between
//! them with no turbofish, no lifetime in any signature, and — the point of the
//! redesign — no where-clause beyond `B: TreeBuilder`.

use bumpalo::Bump;

use crate::ast::{BinaryOp, BoolOp, ComparisonOp, ParsedData, ParsedExpr, ParsedExprKind};
use crate::ast::{ParsedLiteral, ParsedLiteralKind, UnaryOp};
use crate::{Span, Tree, TreeBuilder, TreeDescriptor, TreeNode, Visit};

// --- One builder, hosting both trees -----------------------------------------

#[derive(Clone, Copy)]
pub struct Ast<'arena> {
    arena: &'arena Bump,
}

impl<'arena> Ast<'arena> {
    fn new(arena: &'arena Bump) -> Self {
        Self { arena }
    }
}

/// `Bump` implements none of `Debug`, `PartialEq` or `Hash`, so a builder
/// holding one cannot derive them. Identity is the arena it allocates from.
impl core::fmt::Debug for Ast<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("Ast")
    }
}
impl PartialEq for Ast<'_> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self.arena, other.arena)
    }
}
impl Eq for Ast<'_> {}
impl core::hash::Hash for Ast<'_> {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        core::ptr::hash(self.arena, state);
    }
}

impl<'arena> TreeBuilder for Ast<'arena> {
    type Handle<D: TreeDescriptor> = &'arena TreeNode<Self, D>;
    type List<D: TreeDescriptor> = &'arena [Tree<Self, D>];
    type Str = &'arena str;
    type StrList = &'arena [&'arena str];
    type Bytes = &'arena [u8];

    fn alloc<D: TreeDescriptor>(&self, node: TreeNode<Self, D>) -> Self::Handle<D> {
        self.arena.alloc(node)
    }
    fn alloc_list<D: TreeDescriptor>(
        &self,
        items: impl IntoIterator<Item = Tree<Self, D>, IntoIter: ExactSizeIterator>,
    ) -> Self::List<D> {
        self.arena.alloc_slice_fill_iter(items)
    }
    fn alloc_str(&self, s: &str) -> Self::Str {
        self.arena.alloc_str(s)
    }
    fn alloc_str_list(
        &self,
        items: impl IntoIterator<Item = Self::Str, IntoIter: ExactSizeIterator>,
    ) -> Self::StrList {
        self.arena.alloc_slice_fill_iter(items)
    }
    fn alloc_bytes(&self, bytes: &[u8]) -> Self::Bytes {
        self.arena.alloc_slice_copy(bytes)
    }
}

// --- Construction helpers ----------------------------------------------------

type ExprTree<'arena> = Tree<Ast<'arena>, ParsedExpr>;

impl<'arena> Ast<'arena> {
    /// Spans are irrelevant to these tests, but a node still demands data —
    /// which is the point of requiring it explicitly.
    fn expr(&self, kind: ParsedExprKind<Self>) -> ExprTree<'arena> {
        TreeNode::new(ParsedData::new(Span(0, 0)), kind).alloc(self)
    }

    /// A literal node, wrapped in the expression node that holds it.
    fn lit(&self, kind: ParsedLiteralKind<Self>) -> ExprTree<'arena> {
        let literal =
            TreeNode::<Self, ParsedLiteral>::new(ParsedData::new(Span(0, 0)), kind).alloc(self);
        self.expr(ParsedExprKind::Literal(literal))
    }

    fn int(&self, value: i64) -> ExprTree<'arena> {
        self.lit(ParsedLiteralKind::Int {
            value,
            suffix: None,
        })
    }

    fn ident(&self, name: &str) -> ExprTree<'arena> {
        self.expr(ParsedExprKind::Ident(self.alloc_str(name)))
    }
}

// --- A traversal spanning both trees -----------------------------------------

#[derive(Default)]
struct Census {
    exprs: usize,
    literals: usize,
    idents: usize,
    ints: i64,
}

// Crossing trees costs nothing: the data types come from the descriptors, so
// neither impl needs a bound tying the two trees' data together.
impl<B: TreeBuilder> Visit<B, ParsedExpr, Census> for ParsedExprKind<B> {
    type Output = ();

    fn visit(&self, _data: &ParsedData, ctx: &mut Census) {
        ctx.exprs += 1;
        match self {
            // Crossing into the literal tree is an ordinary child visit.
            ParsedExprKind::Literal(lit) => lit.visit(ctx),
            ParsedExprKind::Ident(_) => ctx.idents += 1,
            ParsedExprKind::None => {}

            ParsedExprKind::Unary { expr, .. }
            | ParsedExprKind::Some(expr)
            | ParsedExprKind::Cast { expr, .. } => expr.visit(ctx),
            ParsedExprKind::Field { value, .. } => value.visit(ctx),
            ParsedExprKind::Lambda { body, .. } => body.visit(ctx),

            ParsedExprKind::Binary { left, right, .. }
            | ParsedExprKind::Boolean { left, right, .. }
            | ParsedExprKind::Comparison { left, right, .. } => {
                left.visit(ctx);
                right.visit(ctx);
            }
            ParsedExprKind::Index { value, index } => {
                value.visit(ctx);
                index.visit(ctx);
            }
            ParsedExprKind::Otherwise { primary, fallback } => {
                primary.visit(ctx);
                fallback.visit(ctx);
            }

            ParsedExprKind::If {
                cond,
                then_branch,
                else_branch,
            } => {
                cond.visit(ctx);
                then_branch.visit(ctx);
                else_branch.visit(ctx);
            }

            ParsedExprKind::Call { callable, args } => {
                callable.visit(ctx);
                for arg in args.iter() {
                    arg.visit(ctx);
                }
            }
            ParsedExprKind::Array(items) | ParsedExprKind::FormatStr { exprs: items, .. } => {
                for item in items.iter() {
                    item.visit(ctx);
                }
            }
        }
    }
}

impl<B: TreeBuilder> Visit<B, ParsedLiteral, Census> for ParsedLiteralKind<B> {
    type Output = ();

    fn visit(&self, _data: &ParsedData, ctx: &mut Census) {
        ctx.literals += 1;
        if let ParsedLiteralKind::Int { value, .. } = self {
            ctx.ints += value;
        }
        // ...and back into the expression tree, via the unit suffix.
        if let Some(suffix) = self.suffix() {
            suffix.visit(ctx);
        }
    }
}

// --- Tests -------------------------------------------------------------------

#[test]
fn builds_a_conditional() {
    let arena = Bump::new();
    let a = Ast::new(&arena);

    // if n > 0 then some [n, 2] else none
    let n = a.ident("n");
    let cond = a.expr(ParsedExprKind::Comparison {
        op: ComparisonOp::Gt,
        left: n,
        right: a.int(0),
    });
    let array = a.expr(ParsedExprKind::Array(a.alloc_list([n, a.int(2)])));
    let root = a.expr(ParsedExprKind::If {
        cond,
        then_branch: a.expr(ParsedExprKind::Some(array)),
        else_branch: a.expr(ParsedExprKind::None),
    });

    let mut census = Census::default();
    root.visit(&mut census);

    // Expressions: if, cond, n, lit(0), some, array, n, lit(2), none.
    assert_eq!(census.exprs, 9);
    // Each literal is an expression node wrapping a literal node.
    assert_eq!(census.literals, 2);
    assert_eq!(census.idents, 2);
    assert_eq!(census.ints, 2);
}

#[test]
fn unit_suffixes_cross_back_into_the_expression_tree() {
    let arena = Bump::new();
    let a = Ast::new(&arena);

    // 9.81`m/s^2`
    let per_second_squared = a.expr(ParsedExprKind::Binary {
        op: BinaryOp::Div,
        left: a.ident("m"),
        right: a.expr(ParsedExprKind::Binary {
            op: BinaryOp::Pow,
            left: a.ident("s"),
            right: a.int(2),
        }),
    });
    let g = a.lit(ParsedLiteralKind::Float {
        value: 9.81,
        suffix: Some(per_second_squared),
    });

    let mut census = Census::default();
    g.visit(&mut census);

    // The suffix is reached from the literal tree: two idents and the `2` inside
    // it are all counted, which only happens by crossing back.
    assert_eq!(census.idents, 2);
    assert_eq!(census.ints, 2);
    assert_eq!(census.literals, 2); // the 9.81 itself, and the exponent 2
}

#[test]
fn a_suffixed_literal_differs_from_a_bare_one() {
    let arena = Bump::new();
    let a = Ast::new(&arena);

    // 100`seconds` versus a bare 100
    let with_unit = a.lit(ParsedLiteralKind::Int {
        value: 100,
        suffix: Some(a.ident("seconds")),
    });
    let bare = a.int(100);

    assert_ne!(with_unit, bare);
}

#[test]
fn every_expression_variant_is_constructible() {
    let arena = Bump::new();
    let a = Ast::new(&arena);

    let x = a.ident("x");
    let one = a.int(1);

    let variants = [
        one,
        a.lit(ParsedLiteralKind::Bool(true)),
        a.lit(ParsedLiteralKind::Str(a.alloc_str("hello"))),
        a.lit(ParsedLiteralKind::Bytes(a.alloc_bytes(b"hi"))),
        a.lit(ParsedLiteralKind::Float {
            value: 1.5,
            suffix: None,
        }),
        a.expr(ParsedExprKind::FormatStr {
            strs: a.alloc_str_list([a.alloc_str("n = "), a.alloc_str("!")]),
            exprs: a.alloc_list([x]),
        }),
        x,
        a.expr(ParsedExprKind::Binary {
            op: BinaryOp::Pow,
            left: x,
            right: one,
        }),
        a.expr(ParsedExprKind::Boolean {
            op: BoolOp::And,
            left: x,
            right: x,
        }),
        a.expr(ParsedExprKind::Comparison {
            op: ComparisonOp::NotIn,
            left: x,
            right: x,
        }),
        a.expr(ParsedExprKind::Unary {
            op: UnaryOp::Not,
            expr: x,
        }),
        a.expr(ParsedExprKind::Call {
            callable: x,
            args: a.alloc_list([one]),
        }),
        a.expr(ParsedExprKind::Index {
            value: x,
            index: one,
        }),
        a.expr(ParsedExprKind::Field {
            value: x,
            field: a.alloc_str("field"),
        }),
        a.expr(ParsedExprKind::Cast {
            expr: x,
            ty_name: a.alloc_str("Int"),
        }),
        a.expr(ParsedExprKind::If {
            cond: x,
            then_branch: one,
            else_branch: one,
        }),
        a.expr(ParsedExprKind::Otherwise {
            primary: x,
            fallback: one,
        }),
        a.expr(ParsedExprKind::Some(x)),
        a.expr(ParsedExprKind::None),
        a.expr(ParsedExprKind::Array(a.alloc_list([x, one]))),
        a.expr(ParsedExprKind::Lambda {
            params: a.alloc_str_list([a.alloc_str("a"), a.alloc_str("b")]),
            body: x,
        }),
    ];

    // Every variant of both enums is built above. Adding a variant breaks the
    // exhaustive matches in `Census`, and this count is the reminder to cover it
    // here too.
    assert_eq!(variants.len(), 21);

    let mut census = Census::default();
    for variant in variants {
        variant.visit(&mut census);
    }
    assert!(census.exprs > variants.len());
    // Five standalone literals, plus the shared `one` reached through seven
    // other variants — a shared subtree is visited once per edge.
    assert_eq!(census.literals, 12);
}

#[test]
fn trees_compare_structurally_across_arenas() {
    fn build<'a>(a: &Ast<'a>) -> ExprTree<'a> {
        a.expr(ParsedExprKind::Binary {
            op: BinaryOp::Add,
            left: a.ident("x"),
            right: a.int(1),
        })
    }

    let left_arena = Bump::new();
    let right_arena = Bump::new();

    // The same expression in two unrelated arenas: equal by structure, distinct
    // in memory. Equality crosses into the literal tree too.
    assert_eq!(
        build(&Ast::new(&left_arena)),
        build(&Ast::new(&right_arena))
    );
}
